CREATE INDEX FLASHCARD_PAGE_FLASHCARD_ID_IX
ON FLASHCARD_PAGE(FLASHCARD_ID);

CREATE INDEX REFRESH_TOKEN_USER_ID_IX
ON REFRESH_TOKEN(USER_ID);

CREATE INDEX RESOLVED_PAGE_USER_ID_IX
ON RESOLVED_PAGE(USER_ID);

CREATE INDEX RESOLVED_PAGE_FLASHCARD_PAGE_ID_IX
ON RESOLVED_PAGE(FLASHCARD_PAGE_ID);